import { describe, expect, it } from 'vitest'
import { Pake, sdpFingerprints, toBase64 } from './pake'
// Generated by the CLI: `go test ./internal/pake -update`
import vectors from '../../testdata/pake.json'

const hex = (s: string) => Uint8Array.from(s.match(/../g)!, b => parseInt(b, 16))
const seeded = (seed: string) => () => hex(seed)

/** Runs a full exchange and reports whether each side accepted the other. */
function pair(host: Pake, peer: Pake): [hostOk: boolean, peerOk: boolean] {
  const hostMac = host.receiveShare(toBase64(peer.share))
  const peerMac = peer.receiveShare(toBase64(host.share))
  return [host.verifyConfirm(toBase64(peerMac)), peer.verifyConfirm(toBase64(hostMac))]
}

describe('compatibility with the CLI', () => {
  for (const c of vectors.cases) {
    it(`derives the same shares and MACs: ${c.name}`, () => {
      const host = new Pake(c.secret, 'host', c.hostFp, c.peerFp, seeded(c.hostSeed))
      const peer = new Pake(c.secret, 'peer', c.hostFp, c.peerFp, seeded(c.peerSeed))
      expect(toBase64(host.share)).toBe(c.hostShare)
      expect(toBase64(peer.share)).toBe(c.peerShare)
      expect(toBase64(host.receiveShare(c.peerShare))).toBe(c.hostMac)
      expect(toBase64(peer.receiveShare(c.hostShare))).toBe(c.peerMac)
      expect(host.verifyConfirm(c.peerMac)).toBe(true)
      expect(peer.verifyConfirm(c.hostMac)).toBe(true)
    })

    it(`authenticates against the CLI's shares with a fresh scalar: ${c.name}`, () => {
      // The CLI plays host with the vector's scalar, we play a random peer
      const peer = new Pake(c.secret, 'peer', c.hostFp, c.peerFp)
      const host = new Pake(c.secret, 'host', c.hostFp, c.peerFp, seeded(c.hostSeed))
      expect(pair(host, peer)).toEqual([true, true])
    })
  }

  for (const c of vectors.fingerprints) {
    it(`canonicalises SDP fingerprints: ${c.name}`, () => {
      expect(sdpFingerprints(c.sdp)).toBe(c.want)
    })
  }
})

describe('Pake', () => {
  const hostFp = 'sha-256 AA', peerFp = 'sha-256 BB'

  it('accepts a matching secret', () => {
    expect(pair(new Pake('a-b', 'host', hostFp, peerFp), new Pake('a-b', 'peer', hostFp, peerFp))).toEqual([true, true])
  })

  it('rejects a wrong secret', () => {
    expect(pair(new Pake('a-b', 'host', hostFp, peerFp), new Pake('a-c', 'peer', hostFp, peerFp))).toEqual([false, false])
  })

  it('rejects swapped fingerprints (MITM)', () => {
    expect(pair(new Pake('a-b', 'host', hostFp, peerFp), new Pake('a-b', 'peer', hostFp, 'sha-256 CC'))).toEqual([false, false])
  })

  it('rejects a reflected MAC', () => {
    expect(pair(new Pake('a-b', 'host', hostFp, peerFp), new Pake('a-b', 'host', hostFp, peerFp))).toEqual([false, false])
  })

  it('answers only one share', () => {
    const p = new Pake('x', 'host', '', '')
    const other = toBase64(new Pake('x', 'peer', '', '').share)
    p.receiveShare(other)
    expect(() => p.receiveShare(other)).toThrow()
  })

  it('rejects the identity element', () => {
    expect(() => new Pake('x', 'host', '', '').receiveShare(toBase64(new Uint8Array(32)))).toThrow()
  })

  it('rejects malformed shares', () => {
    expect(() => new Pake('x', 'host', '', '').receiveShare(toBase64(new Uint8Array(32).fill(0xff)))).toThrow()
    expect(() => new Pake('x', 'host', '', '').receiveShare(toBase64(new Uint8Array(31)))).toThrow()
  })

  it('does not verify before receiving a share', () => {
    expect(new Pake('x', 'host', '', '').verifyConfirm(toBase64(new Uint8Array(32)))).toBe(false)
  })
})
